FROM public.ecr.aws/lambda/python:3.10

COPY pyproject.toml .

# set environment variables
ENV POETRY_VIRTUALENVS_CREATE=false
ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"

# install dependencies
RUN pip3 install poetry
RUN poetry install

COPY . ${LAMBDA_TASK_ROOT}

CMD ["main.handler"]
